### ISSUE TITLE
Will it work on Windows?

### ISSUE THREAD

**Issue by Sandy4321** [benedekrozemberczki/karateclub#1]
Will it work on Windows?

**Comment by benedekrozemberczki** [comment]
It might. It was designed for Linux an OSX.

**Comment by Sandy4321** [comment]
So nobody tried on Windows yet?

**Comment by sbhttchryy** [comment]
I am using it in Win 10 and it works for me

**Comment by benedekrozemberczki** [comment]
That is great.❤❤💙💚💛💜💗
