### ISSUE TITLE
Missing code snippets in readthedocs notes/introduction

### ISSUE THREAD

**Issue by CatChenal** [benedekrozemberczki/karateclub#10]
Under the _Introduction by example_ section, in the _API driven design_ paragraph, it appears that there are two code snippets missing.

The first snippet ought to follow the sentence "This API driven design means that one can create a `DeepWalk` embedding of a Watts-Strogatz graph just like this."

The second one ought to follow the sentence "This can be modified to create a `Walklets` embedding with minimal effort like this."

(Also, changing the full point to a colon would read better.)

**Comment by benedekrozemberczki** [comment]
There were missing spaces. Resolved it. Thank You!
