### ISSUE TITLE
Classifying with graph2vec model

### ISSUE THREAD

**Issue by joseluisfalla** [benedekrozemberczki/karateclub#100]
I'm able to obtain an embedding for a list of NetworkX graphs using graph2vec, and I was wondering if karateclub has a function to make classifications for graphs outside the training set? That is, given my embedding, I want to input a graph outside my original graph list (used in the model) and obtain a list of most similar graphs (something like a "most similar" function).

**Comment by benedekrozemberczki** [comment]
It is called .infer()

**Comment by benedekrozemberczki** [comment]
please star the repo and hit follow

**Comment by joseluisfalla** [comment]
Yes, I've already starred it. Thanks a lot for your help. Really great library.

**Comment by joseluisfalla** [comment]
So, I've trained a model using a list of 40-node graphs, but when I use .infer() on a graph that is not on the list I get two outputs. One has 40 indexes followed by two alphanumeric strings, ie. ['0', '48832e04e4abfa78d379a7a9e19b2948', '038554500505f17f72abe40f2b551e9e', '1', '7f6a09f89662cf23371e883b4cc464b3', 'df5e81a159f616e2b630c792622c6cbb', ... ] and an array of size 128, which I'm assuming is from the dimensionality of the embedding. How can I use this information to obtain the most similar graphs to my input graph from the list of graphs I used to train the model?

**Comment by benedekrozemberczki** [comment]
You can calculate pairwise kernels between the embedding vectors.

**Comment by riyaj8888** [comment]
> So, I've trained a model using a list of 40-node graphs, but when I use .infer() on a graph that is not on the list I get two outputs. One has 40 indexes followed by two alphanumeric strings, ie. ['0', '48832e04e4abfa78d379a7a9e19b2948', '038554500505f17f72abe40f2b551e9e', '1', '7f6a09f89662cf23371e883b4cc464b3', 'df5e81a159f616e2b630c792622c6cbb', ... ] and an array of size 128, which I'm assuming is from the dimensionality of the embedding. How can I use this information to obtain the most similar graphs to my input graph from the list of graphs I used to train the model?

those are WL kernel hashing for nodes
