### ISSUE TITLE
Do we have `model.predict()` in karate club?

### ISSUE THREAD

**Issue by johnnytam100** [benedekrozemberczki/karateclub#105]
Thank you @benedekrozemberczki !
Btw, if I do this way, do you know how to get the embedding of the 300,000 graphs at the end?
Do we have `model.predict()` in karate club?

ps I have already followed and will certainly cite your work.

_Originally posted by @johnnytam100 in https://github.com/benedekrozemberczki/karateclub/issues/103#issuecomment-1183832436_

**Comment by benedekrozemberczki** [comment]
The fit + predict method are good, it is a non learning based sketching
method.

**Comment by johnnytam100** [comment]
Um... I am sorry I don't really get it.
Would you mind pointing to exactly which method?
I am grateful if you can show a small code snippet.
