### ISSUE TITLE
is inductive?

### ISSUE THREAD

**Issue by riyaj8888** [benedekrozemberczki/karateclub#109]
Thanks for open sourcing this repo.
I have one question on Graph2Vec , once i train it  on list of graph to generate embeddings(graph). Can I use it to generate embeddings for new graph? If Yes , how can I generate embeddings for new unseen graph(which is not present in training).

**Comment by benedekrozemberczki** [comment]
Yes, also FEATHER can do that. Graphg2Vec has a method called infer.

**Comment by riyaj8888** [comment]
can we initialize node with some features before passing to Graph2Vec model?

**Comment by benedekrozemberczki** [comment]
Yes, look at the Graph2Vec class and docs.
