### ISSUE TITLE
save graph2vec model

### ISSUE THREAD

**Issue by riyaj8888** [benedekrozemberczki/karateclub#110]
Hi,
How can we save/load the graph2vec model after training?

**Comment by riyaj8888** [comment]
any update man

**Comment by tomlincr** [comment]
@riyaj8888 you can use the standard techniques for scikit-learn models like pickle, joblib etc.

For example:

```python
from joblib import dump, load
dump(model, 'saved_model.joblib') 
model2 = load('saved_model.joblib') 
embedding = model2.get_embedding()
```

Reference: 
> https://scikit-learn.org/stable/model_persistence.html
