### ISSUE TITLE
print in Graph2Vec infer

### ISSUE THREAD

**Issue by mvanma** [benedekrozemberczki/karateclub#113]
First of all, thanks a lot for *Karate Club* !

I noticed while calling `infer()` on a `Graph2Vec` that generated documents are printed out: 

https://github.com/benedekrozemberczki/karateclub/blob/7f516ec37cd469722d45f5759a1d5e4813730714/karateclub/graph_embedding/graph2vec.py#L121

**Comment by benedekrozemberczki** [comment]
Can you open a PR?

**Comment by benedekrozemberczki** [comment]
Solved.
