### ISSUE TITLE
Potential Problem of function _setup_target_matrices in danmf.py

### ISSUE THREAD

**Issue by zslwyuan** [benedekrozemberczki/karateclub#12]
Hi Benedek,

According to my application, some datasets, in which the node indexs might not be continuous, will lead to wrong returned result of function _setup_target_matrices, caused by the expression " nodelist=range(self.graph.number_of_nodes())". To reproduce the problem, you can try a graph generated from: G.add_edges_from([(0,1),(7,8)])
Maybe this is just what I encountered. I walk around the problem by giving the nodes new index.

Best regards,

Tingyuan 

.
=========================================
    def _setup_target_matrices(self, graph):
        """
        Setup target matrix for pre-training process.
        Arg types:
            * **graph** *(NetworkX graph)* - The graph being clustered.
        """
        self.graph = graph
        self.A = nx.adjacency_matrix(self.graph, nodelist=range(self.graph.number_of_nodes()))
        self.L = nx.laplacian_matrix(self.graph, nodelist=range(self.graph.number_of_nodes()))
        self.D = self.L+self.A

**Comment by benedekrozemberczki** [comment]
The introduction that you can access at the link below states that:

Karate Club assumes that the NetworkX graph provided by the user for node
embedding and community detection has the following important properties:

   - Nodes are indexed with integers.
   - There are no orphaned nodes in the graph.
   - The node indexing starts with zero and the indices are consecutive.


https://karateclub.readthedocs.io/en/latest/notes/introduction.html

**Comment by zslwyuan** [comment]
Thanks Benedek! I get it!
