### ISSUE TITLE
Using Feather-Graph with Node Attributes

### ISSUE THREAD

**Issue by safreita1** [benedekrozemberczki/karateclub#125]
Hi @benedekrozemberczki,

Thanks for creating and maintaining this awesome toolbox for graph and node level embedding techniques. I've been using Feather-Graph to embed non-attributed graphs and the results have been fantastic.

**Question:** I'm working on a new problem where graphs contain nodes with attribute information and I wanted to see if it's possible (or makes sense) to extend Feather-Graph to incorporate node attribute information? 

**Current thought process:** I went through the source code and saw that Feather-Node can leverage an attribute matrix, while Feather-Graph uses the log-degree and clustering coefficient as node features. I felt like there could be an opportunity to plug the feature generation process of Feather-Node into Feather-Graph here, but couldn't determine if there would be any downsides to this approach?

I went through your paper "Characteristic Functions on Graphs..." but wasn't able to come to a decision one way or the other. Hoping you can shed some light on it!

Thanks,
Scott

**Comment by benedekrozemberczki** [comment]
Hi there,

It was done to ensure that features are always present. You can use
arbitrary continuous node features and also a higher number.

**Comment by safreita1** [comment]
That's fantastic to hear. 

I would generally assume that the graph embeddings would benefit from leveraging additional node attribute information via the Feather-Node procedure. Does this match your intuition?

**Comment by benedekrozemberczki** [comment]
**Yes, your intuition is completely right.** Finding, good datasets with continuous node features for graph classification was hard. Binary and categorical features do not result in gains. May I ask what are you working on?

**Comment by safreita1** [comment]
Ah I see, that makes sense. I'm actually working with security data that contains many binary and categorical features on the nodes. 

Since Feather-Graph requires continuous node features, I was thinking that running TruncatedSVD on a one-hot encoded categorical feature matrix would result in a suitable setup (the same thing that Feather-Node does)?

**Comment by benedekrozemberczki** [comment]
Yes that sounds good but across grsphs you have to use the same projection

**Comment by safreita1** [comment]
Got it, so ideally we would want to run T-SVD on the entire graph dataset (i.e. one giant node-feature matrix) and then when a new graph comes in, use the same T-SVD component weights to transform it?

**Comment by benedekrozemberczki** [comment]
Yes

**Comment by safreita1** [comment]
Awesome. Thank you for all the help!
