### ISSUE TITLE
A small mistake in the document about the introductions of Graph2Vec and GL2Vec

### ISSUE THREAD

**Issue by Hipkevin** [benedekrozemberczki/karateclub#126]
The introductions of Graph2Vec(at the last) and GL2Vec are almost same in [this page](https://karateclub.readthedocs.io/en/latest/modules/root.html#whole-graph-embedding). I think those are about GL2Vec, cuz the main idea of Graph2Vec is similar to doc2vec.

Here's a sentence from [the source paper](https://arxiv.org/abs/1707.05005)(page 4, Figure 1), may it be useful:
'''
Given a graph _G_, it samples _c_ rooted subgraphs around different nodes that occur in _G_ and uses them analogous to **doc2vec**’s context words and thus learns _G_’s representation.
'''

Thanks for your projects, helped me a lot!

**Comment by benedekrozemberczki** [comment]
No. It is correct - see : "First, the algorithm creates the line graph of each graph in the graph dataset." This is the main difference between these two algos. Have a nice day!
