### ISSUE TITLE
How to use Role2Vec in an inductive way to infer embeddings for unseen nodes

### ISSUE THREAD

**Issue by itsfrank98** [benedekrozemberczki/karateclub#128]
I need an inductive node embedding techniques able to deal with unattributed graphs and Role2Vec seems to be a good options. In the paper, the authors say that it is naturally inductive, but your implementation doesn't provide a **predict** method in order to use the model for producing the embeddings for unseen nodes. So how can this be done?

**Comment by LucaCappelletti94** [comment]
Hi @itsfrank98, I have taken a look at what are the current limitations. The gist is that for inductive methods. You would need to provide a new graph with the new node, sample random walks around the node, compute the features and then use the [infer vector method](https://radimrehurek.com/gensim/models/doc2vec.html#gensim.models.doc2vec.Doc2Vec.infer_vector) to compute the new node embedding.

Such a procedure would intrinsically depend on how you do the walks and likely yield very different results depending on the samples you obtain. I cannot work on exploring possible implementations at this time, but if you do, please consider opening a pull request.

Luca

**Comment by itsfrank98** [comment]
Thank you for your answer, Luca. Unfortunately, at the moment, I am not able to implement such method but I'll keep this in mind if I have time for doing this in future
