### ISSUE TITLE
g2vec_model.infer([test_graph]) returns different embeddings each time I call it

### ISSUE THREAD

**Issue by mohamedelmesawy** [benedekrozemberczki/karateclub#130]
# graph2vec_model.infer([test_graph]) returns different embedding each time I call it.

even I used the same model and it was fitted for only one time, when i call the .infer() function, it returns different embedding. 

- I have also used the seed=42 in the model creation and in the python.
- np.random.seed(42)
- random.seed(42)

**Comment by benedekrozemberczki** [comment]
Is it on the same graph?

**Comment by LucaCappelletti94** [comment]
How many threads are you using? The embedding process uses [Doc2Vec from gensim](https://radimrehurek.com/gensim/models/doc2vec.html), which employs data racing stochastic gradient descent, and therefore it is inherently non-reproducible as there is some collision between threads. These collisions do not notably impact the resulting embedding, but it introduces some extra randomness that is hard to control.

Consider testing to run with a single thread and see whether this difference disappears.
