### ISSUE TITLE
Does GraRep change the input graph ?

### ISSUE THREAD

**Issue by dai-kandeel** [benedekrozemberczki/karateclub#136]
Hello, I have noticed that after using the GraRep algorithm, the number of edges in the input graph increases and it contains self loops! Am I missing something?
![GraRep](https://user-images.githubusercontent.com/44854585/226906500-efcf6f64-f3cf-4486-ab9e-b95c2ed4ae33.png)
I am using version 1.3.3

**Comment by LucaCappelletti94** [comment]
The algorithm necessarily adds the diagonal identity matrix to the adiacendy matrix. That is why you get self loops and 24 more edges.

**Comment by dai-kandeel** [comment]
True, I think it may be also better to do this to a copy and avoid changing the input graph itself. Thanks a lot for the implementation and the quick reply!

**Comment by LucaCappelletti94** [comment]
I will add a warning that, if the graph does not have the necessary self loops, it will be cloned and properly adapted.
