### ISSUE TITLE
Inductive Node Embedding Algorithms in KarateClub

### ISSUE THREAD

**Issue by degschta** [benedekrozemberczki/karateclub#141]
Hello @benedekrozemberczki,

First, I would like to thank you for your work on the KarateClub library. It's a fantastic resource for those of us working in the field of graph representation learning. The collection of network embedding algorithms is quite comprehensive and it's been extremely useful for comparing different methods.

I'm currently working on an academic project that involves graph representation learning, and as part of this project, I need to find out which of the node embedding algorithms included in KarateClub can be considered inductive - i.e., they're capable of generating embeddings for nodes that weren't present in the training data (s.a. [here](https://neo4j.com/docs/graph-data-science/current/machine-learning/node-embeddings/)).

I have some preliminary ideas based on my understanding of the theory behind these algorithms, but I thought it would be most accurate to consult you directly. Is there possibly a juxtaposition of the graph embedding algorithms implemented in KarateClub, maybe in tabular form, that would allow me to directly compare the properties of different embedding algorithms - e.g. properties such as inductiveness, support of directed edges, support of node attributes, etc.? 

Thank you for your time and for your work on this excellent resource.

Best,
degschta

**Comment by zepp133** [comment]
@degschta I would be interested in that too!

@benedekrozemberczki, thank you for the great working you're doing with karateclub!

**Comment by benedekrozemberczki** [comment]
FEATHER is the only one with the right set of node features.
