### ISSUE TITLE
numpy version error

### ISSUE THREAD

**Issue by wyfSunflower** [benedekrozemberczki/karateclub#142]
PS D:\workspace\triangleCountAndLPA\karateclub\examples\whole_graph_embedding> python .\graph2vec_example.py   
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

**Comment by LucaCappelletti94** [comment]
Please, provide more information, such as:
- Your Python version
- Your Numpy version
- What is your OS

**Comment by wyfSunflower** [comment]
thanks for your reply
Python  3.11.4
numpy                         1.22.4
Windows 11 home edition x64

**Comment by wyfSunflower** [comment]
By the way,I was failed to install this library on ubuntu 22.04.2 LTS with Python 3.10.6:
root@DESKTOP-M5G7V2R:/home/gml/triangleCnt/demo# pip3 install karateclub
Collecting karateclub
  Using cached karateclub-1.3.3.tar.gz (64 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      /usr/local/lib/python3.10/dist-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      
      
              It is possible a package already installed in your system
              contains an version that is invalid according to PEP 440.
              You can try `pip install --use-pep517` as a workaround for this problem,
              or rely on a new virtual environment.
      
              If the problem refers to a package that is not installed yet,
              please contact that package's maintainers or distributors.
      
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-rs94y0vc/karateclub_b960d6ff21ee4fd7bb85756fddec4b5c/setup.py", line 46, in <module>
          setup(
        File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 894, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/installer.py", line 39, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 815, in resolve
          dist = self._resolve_dist(
        File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
          env = Environment(self.entries)
        File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1044, in __init__
          self.scan(search_path)
        File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1077, in scan
          self.add(dist)
        File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1096, in add
          dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
        File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2640, in hashcmp
          self.parsed_version,
        File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2694, in parsed_version
          raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
      pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.1build1' (package: distro-info)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by LucaCappelletti94** [comment]
Hi @wyfSunflower, could you please comment how you resolved the issue?

**Comment by wyfSunflower** [comment]
Not solved, failed to install on ubuntu;installed on win11 but run error with numpy version

**Comment by LucaCappelletti94** [comment]
Please refrain from closing this issue if it has not yet been resolved, otherwise, it might never be.

**Comment by ardaeerol** [comment]
relevant issue: 

Building wheels for collected packages: numpy, pandas
  Building wheel for numpy (pyproject.toml): started
  Building wheel for numpy (pyproject.toml): finished with status 'error'
  Building wheel for pandas (pyproject.toml): started
  Building wheel for pandas (pyproject.toml): finished with status 'error'
Failed to build numpy pandas
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  Building wheel for numpy (pyproject.toml) did not run successfully.
  exit code: 1
  
  [202 lines of output]
  setup.py:66: RuntimeWarning: NumPy 1.22.4 may not yet support Python 3.11.
    warnings.warn(
  Running from numpy source directory.
  Processing numpy/random\_bounded_integers.pxd.in
  Processing numpy/random\bit_generator.pyx
  Processing numpy/random\mtrand.pyx
  .....
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
ERROR: Could not build wheels for numpy, pandas, which is required to install pyproject.toml-based projects

python version = 3.11.6
numpy version = 1.26.1
OS = Windows 10 Pro x64

can not even install karateclub..

I tried to install in 2 different PCs, both of them have Windows OS.

**Comment by LucaCappelletti94** [comment]
Can you install numpy and pandas separately? Like, does the following fail?

```bash
pip install pandas numpy -U
```

**Comment by ardaeerol** [comment]
did not work, then I used python 3.10.11 venv and now able to install karateclub.

**Comment by LucaCappelletti94** [comment]
Ok so it seems like we can close as not a KarateClub problem but a pandas/numpy installation problem on Windows, correct?

**Comment by notprg** [comment]
Still having the same issue on ubuntu... Someone solved it?

**Comment by LucaCappelletti94** [comment]
Have you already done as suggested above and `pip install pandas numpy -U` ?

**Comment by LucaCappelletti94** [comment]
> did not work, then I used python 3.10.11 venv and now able to install karateclub

This specifically, @notprg
