### ISSUE TITLE
How to retrieve the mapping between nodes and embeddings with get_embedding() ?

### ISSUE THREAD

**Issue by LPioL** [benedekrozemberczki/karateclub#143]
Hi,

How to retrieve the mapping between nodes and embeddings with get_embedding() ? For example using node2vec ? 

Thank you.

**Comment by LucaCappelletti94** [comment]
The name of the nodes graph is numeric values from 0 to number of nodes. Hence, the matrix you receive already has the order of the node dictionary you provided.
