### ISSUE TITLE
AssertionError: The node indexing is wrong.

### ISSUE THREAD

**Issue by Senejohnny** [benedekrozemberczki/karateclub#149]
First of all thanks for making such an amazing package. 
I have issue with getting an embedding from a multidigraph G, as follow

``` 
from karateclub import Node2Vec
model = Node2Vec()
model.fit(G) 
```
I get the below error: <AssertionError: The node indexing is wrong.>

Any idea why I get this error?

**Comment by LucaCappelletti94** [comment]
Full stack trace please

**Comment by Senejohnny** [comment]
There you are
![image](https://github.com/benedekrozemberczki/karateclub/assets/46810505/b28a381d-f3d4-4bff-a2a8-b70c0f9cefe9)

**Comment by Senejohnny** [comment]
Ah. My extended ChatGPT answered this question. To validate it by you, does it make sens
I do not get the Assertion Error anymore!
![image](https://github.com/benedekrozemberczki/karateclub/assets/46810505/69fc4af4-1c89-4fec-a2ee-e8011c61075b)

**Comment by LucaCappelletti94** [comment]
I think so, although I will have to extend that error message. As it stands, it is not understandable and especially not actionalble.
