### ISSUE TITLE
multiplex graph support

### ISSUE THREAD

**Issue by xiachenrui** [benedekrozemberczki/karateclub#161]
Thanks for your great works!

I want to know if karateclub can support multiplex graph yet.

Any clarification will be helpful.

Best!

**Comment by rjurney** [comment]
Karate Club takes initial node properties as a feature for some embeddings. As to edges… there is no explicit type in the library’s graph embeddings. [Attributed node embeddings](https://karateclub.readthedocs.io/en/latest/modules/root.html#attributed-node-embedding) use node feature script matrices. Node type could be encoded as an integer feature there. Check out the [docs site’s link](https://karateclub.readthedocs.io/en/latest/notes/resources.html#structural-node-embedding) to papers of the algorithms karateclub supports.

Not sure I was that helpful :)

**Comment by xiachenrui** [comment]
Thanks ! @rjurney.

I think karateclub not supports multiplex graph yet.

**Comment by rjurney** [comment]
> Thanks ! @rjurney.
> 
> I think karateclub not supports multiplex graph yet.

I would check out PyG. I believe you can embed nodes using its multiplex or knowledge graph models. https://pyg.org/
