### ISSUE TITLE
Problem with ED-mot

### ISSUE THREAD

**Issue by rahram2010** [benedekrozemberczki/karateclub#20]
I don't think Ed-mot is properly implemented in this package, in the paper, the connected components are not just joined into a giant clique as is performed in the implementation of this. In the paper the connected components are partitioned into so called modules by the Louvain community detection algorithm and and then those nodes in the modules are connected to form a clique, this is a subtle point but important for the algorithm. This is not the Ed-mot algorithm as described in the paper.

**Comment by benedekrozemberczki** [comment]
The algorithm implemented here is equivalent to the one in the paper. Please take a closer look.
