### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by zolekode** [benedekrozemberczki/karateclub#21]
Hi, for attribute based approaches, is there a way to get embeddings at test time on unseen data ? 
For example: after `embedder.fit(graph, X)` , can i input for example `embbeder.predict([some unseen input features])` to get embeddings at test time ?

**Comment by benedekrozemberczki** [comment]
Hi there,

A large number of those methods is transductive - which means that you could not make a consistent API and for certain classes, the predict / score methods should not return anything.

**Comment by benedekrozemberczki** [comment]
E.g. from the implemented methods only MUSAE is inductive.

**Comment by zolekode** [comment]
Hi, thanks a lot this helps deffo
