### ISSUE TITLE
Graphwave broken...

### ISSUE THREAD

**Issue by wanglili-dartmouth** [benedekrozemberczki/karateclub#22]
It worked before but is broken now in the newest version

**Comment by benedekrozemberczki** [comment]
What is the error message?

**Comment by wanglili-dartmouth** [comment]
It says AttributeError: 'GraphWave' object has no attribute 'number_of_nodes'
I read your source code and I guess in line 72 it should be  'self._number_of_nodes',  I fixed it but it still return other errors.

**Comment by benedekrozemberczki** [comment]
What is your Karate Club version?

**Comment by benedekrozemberczki** [comment]
What is the other error?

**Comment by wanglili-dartmouth** [comment]
the other error is :  AttributeError: 'GraphWave' object has no attribute 'eigen_vectors'
