### ISSUE TITLE
Graph embedding with direction and weight

### ISSUE THREAD

**Issue by john-wick-ksg** [benedekrozemberczki/karateclub#23]
Hi, thanks for your great work.

I'm looking for a way to make whole graph embeddings with directed edges and multi dimension weights for nodes.
Do you know which API can do it?
I have tried all of graph embedding API in this, but could not see find a good one.
TIA.

**Comment by benedekrozemberczki** [comment]
Sorry I do not. After we submit this paper I will do a major refactoring to include these in this package.
