### ISSUE TITLE
Graph2Vec: ValueError: Graph is not connected. Please see requirements.

### ISSUE THREAD

**Issue by swayson** [benedekrozemberczki/karateclub#25]
Hi there,

I tried to run Graph2Vec and ensured the following is true:
- The graph is undirected.
- Nodes are indexed with integers.
- There are no orphaned nodes in the graph.
- The node indexing starts with zero and the indices are consecutive.

Yet, still get a `ValueError: Graph is not connected. Please see requirements.` Any insights as to what may be the problem.

I removed orphaned nodes and relabeled the indices.
```
G.remove_nodes_from(list(nx.isolates(G)))
mapping = {id: i for i, id in enumerate(G.nodes())}
H = nx.relabel_nodes(G, mapping)

from karateclub import Graph2Vec

model = Graph2Vec()
model.fit([H])
X = model.get_embedding()
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\...\lib\site-packages\karateclub\estimator.py in _check_connectivity(self, graph)
     45             if not connected:
---> 46                 raise ValueError("Graph is not connected. Please see requirements.")
     47         except:

ValueError: Graph is not connected. Please see requirements.
```

**Comment by benedekrozemberczki** [comment]
Is the graph connected? You can remove the requirement that is being checked if you want to use Graph2Vec, it should run without orphaned nodes.
