### ISSUE TITLE
Size of BoostNE embeddings

### ISSUE THREAD

**Issue by malteos** [benedekrozemberczki/karateclub#26]
Hi all,

thanks for this great piece of software! I just started using your BoostNE implementations and was wondering why the dimensions of the output embeddings do not follow the `dimensions` parameter. The output instead has the size of  `d=dimensions+dimensions*iterations`. 

Is this a bug or a feature?

Best
Malte

**Comment by benedekrozemberczki** [comment]
It is a property of the iterative boosting. Dimensions is the number of dimensions for a single embedding.

**Comment by benedekrozemberczki** [comment]
Did you read the paper?

**Comment by malteos** [comment]
> Did you read the paper?

I just scanned through but yeah that's actually a good idea :D

Thanks for the quick reply.
