### ISSUE TITLE
GL2vec : RuntimeError: you must first build vocabulary before training the model

### ISSUE THREAD

**Issue by hug0prevoteau** [benedekrozemberczki/karateclub#27]
Hello, 
First thanks for your work, it's just great.

However, I have an error while trying to run GL2vec on my dataset, while it works perfectly with the example.
Where is exactly this type of error coming from ?

Thanks in advance

**Comment by benedekrozemberczki** [comment]
Could you give more details?

**Comment by hug0prevoteau** [comment]
Sure,

**Comment by hug0prevoteau** [comment]
Sure, 
I checked my graph meets all the requirements of the library

here is the complete error:

RuntimeError                              Traceback (most recent call last)
<ipython-input-125-654e9d58a45d> in <module>
      1 model = GL2Vec()
      2 
----> 3 model.fit(graphs)
      4 model.get_embedding()

~\Anaconda3\lib\site-packages\karateclub\graph_embedding\gl2vec.py in fit(self, graphs)
     74                         epochs=self.epochs,
     75                         alpha=self.learning_rate,
---> 76                         seed=self.seed)
     77 
     78         self._embedding = [model.docvecs[str(i)] for i, _ in enumerate(documents)]

~\Anaconda3\lib\site-packages\gensim\models\doc2vec.py in __init__(self, documents, corpus_file, dm_mean, dm, dbow_words, dm_concat, dm_tag_count, docvecs, docvecs_mapfile, comment, trim_rule, callbacks, **kwargs)
    617                 documents=documents, corpus_file=corpus_file, total_examples=self.corpus_count,
    618                 total_words=self.corpus_total_words, epochs=self.epochs, start_alpha=self.alpha,
--> 619                 end_alpha=self.min_alpha, callbacks=callbacks)
    620 
    621     @property

~\Anaconda3\lib\site-packages\gensim\models\doc2vec.py in train(self, documents, corpus_file, total_examples, total_words, epochs, start_alpha, end_alpha, word_count, queue_factor, report_delay, callbacks)
    811             sentences=documents, corpus_file=corpus_file, total_examples=total_examples, total_words=total_words,
    812             epochs=epochs, start_alpha=start_alpha, end_alpha=end_alpha, word_count=word_count,
--> 813             queue_factor=queue_factor, report_delay=report_delay, callbacks=callbacks, **kwargs)
    814 
    815     @classmethod

~\Anaconda3\lib\site-packages\gensim\models\base_any2vec.py in train(self, sentences, corpus_file, total_examples, total_words, epochs, start_alpha, end_alpha, word_count, queue_factor, report_delay, compute_loss, callbacks, **kwargs)
   1079             total_words=total_words, epochs=epochs, start_alpha=start_alpha, end_alpha=end_alpha, word_count=word_count,
   1080             queue_factor=queue_factor, report_delay=report_delay, compute_loss=compute_loss, callbacks=callbacks,
-> 1081             **kwargs)
   1082 
   1083     def _get_job_params(self, cur_epoch):

~\Anaconda3\lib\site-packages\gensim\models\base_any2vec.py in train(self, data_iterable, corpus_file, epochs, total_examples, total_words, queue_factor, report_delay, callbacks, **kwargs)
    534             epochs=epochs,
    535             total_examples=total_examples,
--> 536             total_words=total_words, **kwargs)
    537 
    538         for callback in self.callbacks:

~\Anaconda3\lib\site-packages\gensim\models\base_any2vec.py in _check_training_sanity(self, epochs, total_examples, total_words, **kwargs)
   1185 
   1186         if not self.wv.vocab:  # should be set by `build_vocab`
-> 1187             raise RuntimeError("you must first build vocabulary before training the model")
   1188         if not len(self.wv.vectors):
   1189             raise RuntimeError("you must initialize vectors before training the model")

RuntimeError: you must first build vocabulary before training the model

**Comment by benedekrozemberczki** [comment]
Most probably the corpus is downsampled too heavily. Read about
downsampling of Doc2Vec and Word2Vec.

**Comment by benedekrozemberczki** [comment]
Was this helpful?

**Comment by hug0prevoteau** [comment]
It doesn't work even with a single graph

**Comment by hug0prevoteau** [comment]
![image](https://user-images.githubusercontent.com/62139503/81421964-9ddbe080-9152-11ea-9b87-7378f49477ab.png)

**Comment by benedekrozemberczki** [comment]
Given the downsampling constraint, it should not.

**Comment by hug0prevoteau** [comment]
Ok my bad, I fixed it, I added the centrality to the nodes as 'feature', comes from a misunderstanding from the documentation.

Thanks for your help

**Comment by HodaMemar** [comment]
> Ok my bad, I fixed it, I added the centrality to the nodes as 'feature', comes from a misunderstanding from the documentation.
> 
> Thanks for your help

Hello 
I need guidance to use this model. Exactly how the input graph should be given to the model. A simple example would be very helpful.

**Comment by hug0prevoteau** [comment]
These informations are detailed in "graph_embedding_test.py"

You simply need to feed a list of networkx graphs into the model.

You can use this:
`graphs = [nx.newman_watts_strogatz_graph(50, 5, 0.3) for _ in range(100)]
model = Graph2Vec()
model.fit(graphs)
embedding = model.get_embedding()`

As of may, the Graph2Vec implementation didn't consider the weights on the edges, I don't know if they do now.

**Comment by benedekrozemberczki** [comment]
There are examples in the folder with the same name.

**Comment by HodaMemar** [comment]
Thank you for your reply and help.

**Comment by AkshatSood** [comment]
Is there a difference between providing a list of graphs as an input to the model, or, running the model on each graph at a time?

**Comment by benedekrozemberczki** [comment]
Please read the relevant papers.
