### ISSUE TITLE
Extreme performance issues due to networkx

### ISSUE THREAD

**Issue by franz101** [benedekrozemberczki/karateclub#28]
Hi,
I love this package. Is there any plan to move away from networkx?
Have a look at the comparison: 
https://www.timlrx.com/2019/05/05/benchmark-of-popular-graph-network-packages/

NetworkX is the slowest.

Looking forward for a short reply.

**Comment by benedekrozemberczki** [comment]
As the paper is currently under review there is not right now.

**Comment by franz101** [comment]
@benedekrozemberczki thanks for your quick reply. My teachers recently showed us karateclub. I'm absolutely grateful for your work! Looking forward for future releases!

**Comment by benedekrozemberczki** [comment]
Teachers? Which university? :)
