### ISSUE TITLE
Graph Embedding with Node and Edge Features

### ISSUE THREAD

**Issue by Marvinmw** [benedekrozemberczki/karateclub#29]
hi,
it is an awesome tool. I have some graphs. Each node and and edge has a vector feature. 
I do not sure how to use kateclub with these graphs. What is the input format of graphs?

**Comment by benedekrozemberczki** [comment]
The embedding methods included only allow node attributes.

**Comment by benedekrozemberczki** [comment]
I would suggest that you read the relevant papers about MUSAE, BANE, TADW etc.
