### ISSUE TITLE
Does karateclub support an undirected weight graph?

### ISSUE THREAD

**Issue by democheng** [benedekrozemberczki/karateclub#30]
Hello:
    I'm lucky to find this great project.
    I‘m solving a problem modeled as an undirected weight graph, and I read the source code of 'EgoNetSplitter', 'MNMF', 'GEMSEC', but there is no 'edge weight'.
    Does karateclub support an undirected weight graph?

**Comment by benedekrozemberczki** [comment]
The paper and the documentation makes it clear that the 1.0.x releases do not support weighted graphs. Please read those.
