### ISSUE TITLE
Node feature

### ISSUE THREAD

**Issue by Marvinmw** [benedekrozemberczki/karateclub#31]
I checked the sample dataset and source code. It seems that the node feature is a value. Is it possible to use vector feature?

**Comment by benedekrozemberczki** [comment]
Which dataset and which model?

**Comment by Marvinmw** [comment]
for example, facebook . And for graph-level, reddit10k has no extra feature.
And my issue is that I do not how to generate data from myself dataset. Can you tell me what is the data format for the model?

**Comment by benedekrozemberczki** [comment]
This is informative:

https://github.com/benedekrozemberczki/karateclub/blob/master/examples.py

Also if you read the paper you will get a solid understanding.

**Comment by benedekrozemberczki** [comment]
Also the documentation on read the docs always describes the types of inputs that it requires with proper typing notation,
