### ISSUE TITLE
GEMSEC example

### ISSUE THREAD

**Issue by bkj** [benedekrozemberczki/karateclub#32]
Hi --

I'm trying to use your GEMSEC implementation, but having a little bit of trouble figuring out how to run it on an example dataset.  Are you able to share an example of training and evaluating the model on one of the datasets here?

Thanks!
~ Ben

**Comment by jestinjoy** [comment]
```
import networkx as nx
from karateclub import GEMSEC
g = nx.newman_watts_strogatz_graph(1000, 20, 0.05)
splitter = GEMSEC(clusters=10)
splitter.fit(g)
print(splitter.get_memberships())
```
