### ISSUE TITLE
No documentation in official pypi.org

### ISSUE THREAD

**Issue by kandarpkakkad** [benedekrozemberczki/karateclub#33]
There is no documentation in pypi.org "karateclub" i.e. https://pypi.org/project/karateclub/ page. You can create it using Sphinx very easily and it will create HTML pages as well if you want to publish the documentation on your own.

**Comment by benedekrozemberczki** [comment]
https://karateclub.readthedocs.io/en/latest/ ? ;)

**Comment by kandarpkakkad** [comment]
Ohk!!
