### ISSUE TITLE
TADW where is the text feature?

### ISSUE THREAD

**Issue by myrainbowandsky** [benedekrozemberczki/karateclub#34]
https://github.com/benedekrozemberczki/karateclub/blob/300bbbd367b8b9388ac7eb77d4ff756751a38263/karateclub/node_embedding/attributed/tadw.py#L90 

and 

https://github.com/benedekrozemberczki/karateclub/blob/bd8fb5ddad5b82f575fa35aef74de8d1fce258be/karateclub/node_embedding/attributed/feathernode.py#L82

are identical . they are in different papers but the comments are identical. 
in TADW there is text feature matrix. where is it?

**Comment by benedekrozemberczki** [comment]
Please read the TADW paper in detail and look at the actual code of the TADW reference implementation . One of the first pre-processing steps is SVD. The same thing happens here.
