### ISSUE TITLE
Wrong requirement sklearn

### ISSUE THREAD

**Issue by fjsj** [benedekrozemberczki/karateclub#35]
Hi, it looks like this library is using the wrong requirement `sklearn`. It should be `scikit-learn`.

The requirement is here:
https://github.com/benedekrozemberczki/karateclub/blob/852000a163e4fbc7dafba425a90a91e85ba13d58/setup.py#L3-L4

If you visit `sklearn` PyPI page, you'll see it says to use `scikit-learn` instead: https://pypi.org/project/sklearn/

**Comment by benedekrozemberczki** [comment]
https://stackoverflow.com/questions/38733220/difference-between-scikit-learn-and-sklearn

**Comment by fjsj** [comment]
From your link, this answer: https://stackoverflow.com/a/54573708/145349
The correct is `scikit-learn`, altough `sklearn` might be doing what you're expecting.
If you `pip install` manually, you'll see it's redirecting to `scikit-learn`:

```
% pip install sklearn
Collecting sklearn
  Using cached https://files.pythonhosted.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz
Collecting scikit-learn (from sklearn)
  Using cached https://files.pythonhosted.org/packages/32/37/51bf33e269be272255ab6a1c172e15b930bcf33316616efc82e0759ca4ff/scikit_learn-0.23.1-cp37-cp37m-macosx_10_9_x86_64.whl
```

**Comment by fjsj** [comment]
Also note it'll break when you try to lock versions:
```
% pip install "sklearn==0.23.1" 
Collecting sklearn==0.23.1
  ERROR: Could not find a version that satisfies the requirement sklearn==0.23.1 (from versions: 0.0)
ERROR: No matching distribution found for sklearn==0.23.1
```

**Comment by benedekrozemberczki** [comment]
I just made a push with the version change.
