### ISSUE TITLE
A question for BANE, TENE and TADW 

### ISSUE THREAD

**Issue by Barron429** [benedekrozemberczki/karateclub#36]
Hi,

I am trying to use there 3 methods, but my graph is not connected:

site-packages/karateclub/estimator.py", line 50, in _check_connectivity
raise ValueError("Graph is not connected. Please see requirements.")

Could I know if it is necessary to make graph connected? and how to avoid this problem?

Thanks

**Comment by benedekrozemberczki** [comment]
You can remove the connectedness check. We created a pretty specific
interface for checking the requirements, in later versions I might remove
that requirement.

**Comment by Barron429** [comment]
Thanks for your reply. 
Could I know if removing the connectedness check will not hurt the performance of these 3 methods?

**Comment by benedekrozemberczki** [comment]
BANE should not be hurt as it is an inductive method and context is defined
by features. TADW and TENE are transductive - removing the condition is
risky.
