### ISSUE TITLE
The way to do overlapping community detection with DANMF

### ISSUE THREAD

**Issue by kkonevets** [benedekrozemberczki/karateclub#38]
I can find lots of overlapping community detection algorithms in this library but only EgoNetSplitter returns multiple clusters for a node. How can I use DANMF to find overlapping clusters? Please give a hint.

**Comment by benedekrozemberczki** [comment]
Use np.argmax over the embedding matrix at the bottle neck.

**Comment by kkonevets** [comment]
But if I use np.argmax it will give me only one label for a node, I need more. Can I use some kind of a threshold to to select clusters , something like this:
```python
    splitter = DANMF()
    splitter.fit(g)
    membership = []
    for row in np.where(splitter._P > threshold):
        membership.append(np.where(row)[0])
```
If so, how can I choose a threshold? I gues `_P` matrix is not a probability matrix?

**Comment by benedekrozemberczki** [comment]
No it is not. You could come up with normalization tactics. I do not think
that there is a clean nice solution sadly.

**Comment by mamintoosi** [comment]
Hi Dear Konevets,
In the following code, after normalizing P, max_in_row is the membership score of the winner cluster in which the node i is belongs to this cluster. Other clusters in which their memberships are above some threshold (related to winner cluster's membership score) will be assigned to this node, as overlapping clusters.

`            P = normalize(model._P, axis=1)
            membership_closeness = 0.25
            near_clusters = []
            for i in range(P.shape[0]):
                row = P[i]
                max_in_row = np.max(row)
                npw = np.where(row >= (max_in_row*membership_closeness))
                tmp = npw[0].tolist()
                near_clusters.append(tmp)
`
Note that we have some problems with empty clusters.
I hope it be correct.
