### ISSUE TITLE
Enhancement with Node2Vec and GraphSAGE

### ISSUE THREAD

**Issue by imohitmayank** [benedekrozemberczki/karateclub#42]
Hi, nice package! Just wanted to know if there is any plan to support additional papers like Node2Vec and GraphSage. Especially Node2Vec, as it's an extension (generalization) of existing DeepWalk. Thnx!

**Comment by benedekrozemberczki** [comment]
Dear Mohit,

GraphSage is out of the scope of the framework. I might add Node2Vec later.

Bests,

Benedek

**Comment by imohitmayank** [comment]
Cool, btw seems Node2Vec will require modification of `RandomWalker` to add the return and in-out parameters. Let me know if you are accepting pull requests.

**Comment by benedekrozemberczki** [comment]
Yes. Node2Vec is DeepWalk with return and in-out set to be 1. As the second-order random walk is slow, you would need a first and second-order random walker class and You would also need to create a separate model class. If you are happy to do that, you follow the coding conventions and write the appropriate tests I am happy to approve your PR.
