### ISSUE TITLE
Having some difficulty with embedding graphs and nodes

### ISSUE THREAD

**Issue by ChristopherMarais** [benedekrozemberczki/karateclub#49]
Good day, 

I have been trying to create embeddings for nodes in a graph and for whole graphs using the FeatherNode and FeatherGraph functions. 

What am I doing wrong? is it because not all the nodes in the graphs are connected? How can I get around this?

Regards
Chris

AssertionError                            Traceback (most recent call last)
<ipython-input-15-2c00de80a277> in <module>
      1 model = FeatherNode()
----> 2 model.fit(G, expression.values)
      3 emb = model.get_embedding()

~\anaconda3\envs\MIT_807_P38\lib\site-packages\karateclub\node_embedding\attributed\feathernode.py in fit(self, graph, X)
    109         """
    110         self._set_seed()
--> 111         self._check_graph(graph)
    112         X = self._create_reduced_features(X)
    113         A_tilde = self._create_A_tilde(graph)

~\anaconda3\envs\MIT_807_P38\lib\site-packages\karateclub\estimator.py in _check_graph(self, graph)
     60     def _check_graph(self, graph: nx.classes.graph.Graph):
     61         """Check the Karate Club assumptions about the graph."""
---> 62         self._check_connectivity(graph)
     63         self._check_directedness(graph)
     64         self._check_indexing(graph)

~\anaconda3\envs\MIT_807_P38\lib\site-packages\karateclub\estimator.py in _check_connectivity(self, graph)
     42         """Checking the connected nature of a single graph."""
     43         connected = nx.is_connected(graph)
---> 44         assert connected, "Graph is not connected."
     45 
     46 

AssertionError: Graph is not connected.

**Comment by ChristopherMarais** [comment]
I would like to perform link prediction and include the orphaned nodes for this. How do I approach this problem? I have a single adjacency matrix with multiple subgraphs that may not all be connected to one another.

**Comment by benedekrozemberczki** [comment]
1. Regarding the orphaned nodes - I do not think that any embedding method
is particularly meaningful in that case. I have to think about that.
2. Use separate graphs with indexing starting at zero, as it is a
completely inductive method every node will be embedded in the same space.
Use Feather N iteratively.

**Comment by ChristopherMarais** [comment]
Nevermind, I figured it out. I forgot to remove the orphan nodes from my feature matrix. 

sorry for bothering you here, but I really want to say how much I appreciate your quick response and I am fully enjoying using karateclub
