### ISSUE TITLE
About GL2vec

### ISSUE THREAD

**Issue by cheezy88** [benedekrozemberczki/karateclub#5]
Hello,
thanks for the awesome work!!

It seems that there are 2 mistakes in the implementation of GL2vec module.

The first one is :  

in the code below,
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
    def _create_line_graph(self, graph):
        r"""Getting the embedding of graphs.
        Arg types:
            * **graph** *(NetworkX graph)* - The graph transformed to be a line graph.
        Return types:
            * **line_graph** *(NetworkX graph)* - The line graph of the source graph.
        """
        graph = nx.line_graph(graph)
        node_mapper = {node: i for i, node in enumerate(graph.nodes())}
        edges = [[node_mapper[edge[0]], node_mapper[edge[1]]] for edge in graph.edges()]
        line_graph = nx.from_edgelist(edges)
        return line_graph
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
when converting graph G to line graph LG, the method "_create_line_graph()" ignores the edge attribute of G. (It means that there will be no node arrtibutes in LG)
so consequently, the method "WeisfeilerLehmanHashing" will not use the attribute information, and will always use the structural information (degree) instead.

The second one is :

The GL2vec module only returns the embedding of line graph.
But in the original paper of GL2vec, they concatenate the embedding of graph and of line graph.  
Then named the framework "GL2vec", which means "Graph and Line graph to vector".

Only use the embedding of line graph for downstream task may lead to worse performance.

We noticed that when applying the embeddings to the graph classification task, (when graph both have node attribute and edge attribute) the performance (accuracy) are as follow:
concat(G , LG) > G > LG

Hope it helps :)

**Comment by benedekrozemberczki** [comment]
Problem 1. I agree, the original datasets had node features - how did you create the edge features? Simple concatenation?

Problem 2. With the current API it generally means the concatenation of the current Gl2Vec embedding matrix with a Graph2Vec embedding matrix.

**Comment by cheezy88** [comment]
Thanks for the reply!

For Problem1: 

Some benchmark dataset(or user's own dataset) may have edge features, for example in the dataset from chemical field, the edge features(chemical bonds) are always available.

I wonder if it is possible to fix the GL2vec module to handle both the two cases (1)graph with edge feature, (2)without edge feature. Same as the Graph2vec module.
Because in Graph2vec module, user can chose to use node feature or not, by setting "attributed" to True/False. However, in GL2vec module, user cannot chose to use the edge feature, since the "attributed" is set to False.  Also when converting graph to line graph the edge features are ignored.

hope the awsome library "karateclub" becomes more powerful :)


For Problem2:

I am sorry, I can't find the code corresponding to the concatenation processing.  
Did I miss something? If so, would you mind show me that?

**Comment by zslwyuan** [comment]
Hello @cheezy88 @benedekrozemberczki ,

   Awesome work!
   +1 for the @cheezy88 's consideration :). 
   For GL2vec, the node features are important, I am really curious that if I directly change the fit function of GL2vec to let it make use of the node features, will there be any potential risk? 

^_^

**Comment by benedekrozemberczki** [comment]
This would require some thinking on my side. The modification that I
promised is still on the back log for the project. I did not forget.

**Comment by yuvalgrossman** [comment]
Hi! 
@benedekrozemberczki 
This is just awesome project! I recently started to work with graphs and your work really make it easy, so thanks! 
Regarding the two issues @cheezy88 pointed, I tried to solve them and add a PR. 
Actually this is my first PR to public project and I am really not sure I've done it correctly, but for me my solution worked. I will be glad to some review
I demonstrated and visualized it in [this notebook](https://colab.research.google.com/drive/1U4Yv3Vh0eTN7w_aWrD9qpqO6Syvv4l7D).

**Comment by benedekrozemberczki** [comment]
Hi there,

For me it fails for some reason, as I said I will look at the problem.

Regards,

Benedek

**Comment by yuvalgrossman** [comment]
Another issue is with graphs without edges. I simply fixed it in the fit function using a condition: 
`graphs = [self._create_line_graph(graph) if len(graph.edges()) else nx.Graph() for graph in graphs]
`

I'm not sure if it is better to create an empty graph (like I did here) or just take only graphs with edges.

**Comment by benedekrozemberczki** [comment]
https://karateclub.readthedocs.io/en/latest/notes/introduction.html

Karate Club assumes that the NetworkX graph provided by the user for node
embedding and community detection has the following important properties:

   - Nodes are indexed with integers.
   - There are no orphaned nodes in the graph.
   - The node indexing starts with zero and the indices are consecutive.
