### ISSUE TITLE
Whole graph embeddings when graph is not connected

### ISSUE THREAD

**Issue by foxtrotmike** [benedekrozemberczki/karateclub#50]
Thank you for the awesome library!
I have been trying to embed whole graphs but my each of my graphs is not connected. Is it possible to get graph embedding for such graphs?

**Comment by benedekrozemberczki** [comment]
Yes, you should modify the model meta class - you should remove the
connectedness assertion.

**Comment by benedekrozemberczki** [comment]
Could you start the repo and hit a follow?

**Comment by OmranKaddah** [comment]
Why did you make the connectedness assumption?

**Comment by benedekrozemberczki** [comment]
API consistency and certain methods only work on connected methods.
