### ISSUE TITLE
Ask question about model HOPE

### ISSUE THREAD

**Issue by Billy1900** [benedekrozemberczki/karateclub#52]
This is part of code of HOPE
<pre>
    def _do_rescaled_decomposition(self, S):
        """
        Decomposing the similarity matrix.
        """
        U, sigmas, Vt = sps.linalg.svds(S, k=int(self.dimensions/2))
        sigmas = np.diagflat(np.sqrt(sigmas))
        self._left_embedding = np.dot(U, sigmas)
        self._right_embedding = np.dot(Vt.T, sigmas)

    def fit(self, graph: nx.classes.graph.Graph):
        """
        Fitting a HOPE model.

        Arg types:
            * **graph** *(NetworkX graph)* - The graph to be embedded.
        """
        self._set_seed()
        self._check_graph(graph)
        S = self._create_target(graph)
        self._do_rescaled_decomposition(S)
</pre>
It uses the svd, but in paper (https://www.kdd.org/kdd2016/papers/files/rfp0184-ouA.pdf), it uses approximation of high-order proximity which could improve the efficiency to some extent. The algorithm as follows,
![image](https://user-images.githubusercontent.com/32431813/95462756-85464f80-09aa-11eb-89ab-27bc7fc94bcf.png)

**Comment by benedekrozemberczki** [comment]
Sure. Do you want to include it with a PR?

**Comment by Billy1900** [comment]
sorry, I am not planning to reproduce his code, I am overwhelmed recently.
