### ISSUE TITLE
Graph Embeddings using node features and inductivity

### ISSUE THREAD

**Issue by TrovatelliT** [benedekrozemberczki/karateclub#53]
Hello,

First of all thank you for this amazing library! I have a serie of small graphs where each node contains features and I am trying to learn graph-level embedding in an unsupervised manner.
However, I couldn't find how to load node features in the graphs before feeding them to a graph embedding algorithm. Could you describe the input needed by the algorithms ?

Also, is it possible to generate embedding with some sort of `forward` function once the models are trained (without retraining the model) ? I.e. does the library support inductivity ?

Thank you!

**Comment by benedekrozemberczki** [comment]
Hi there,

I am happy if you like the library. Could you star it? I also create other great content so it might worth following me.

Generally, you can only have a single feature if you use Graph2Vec. You have to set the appropriate feature of the NetworkX graph -- look at the documentation it is under the "feature" key. Other methods are purely topological and some of them are inductive:

- FEATHER
- NetLSD
- FGSD

If the features are continuous you could modify FEATHER to accommodate those.

**Comment by JeffersonH44** [comment]
hello @benedekrozemberczki, reviewing your FEATHER-G algorithm for graph level embedding I don't see any usage of the node features provided to the graph, you only use the degree and the clustering coefficient of each node, or at least not [here](https://github.com/benedekrozemberczki/karateclub/blob/master/karateclub/graph_embedding/feathergraph.py#L66).

Also many thanks for your implementations.

**Comment by benedekrozemberczki** [comment]
Yes, this implementation assumes topological features. Look at the FEATHER
repo.

**Comment by JeffersonH44** [comment]
Sorry to bother you again, I'm not able to see any node features used on the FEATHER repo. Many thanks

**Comment by benedekrozemberczki** [comment]
https://github.com/benedekrozemberczki/FEATHER
