### ISSUE TITLE
Is it possible to save embeddings for later use?

### ISSUE THREAD

**Issue by RinyBua** [benedekrozemberczki/karateclub#54]
Hi

Is there any way to save the embedding for later use as a file, e.g., result.emb?

The output file has n+1 lines for a graph with n vertices. The first line has the following format:
num_of_nodes dim_of_representation

The next n lines are as follows:
node_id dim1 dim2 ... dimd

where dim1, ... , dimd is the d-dimensional representation learned by the embedding method

Ex:
34 2
33 1.4270996 -1.6193795
0 -1.2400748 -1.3776317
32 1.6967283 -1.7419897
.
.
.
11 -1.193218 -1.3673347

Thank you

**Comment by benedekrozemberczki** [comment]
You could use pandas for this.

**Comment by benedekrozemberczki** [comment]
Could you star the repository and follow me on github?
