### ISSUE TITLE
HOPE for directed graphs?

### ISSUE THREAD

**Issue by paul-tqh-nguyen** [benedekrozemberczki/karateclub#55]
The [HOPE paper](https://www.kdd.org/kdd2016/papers/files/rfp0184-ouA.pdf) makes it seem like HOPE is intended to embed nodes in a directed graph. 

However, it seems that the [HOPE implementation in karateclub](https://github.com/benedekrozemberczki/karateclub/blob/master/karateclub/node_embedding/neighbourhood/hope.py) only supports undirected graphs.
* [Line 48](https://github.com/benedekrozemberczki/karateclub/blob/master/karateclub/node_embedding/neighbourhood/hope.py#L48) calls [`Estimator._check_graph`](https://github.com/benedekrozemberczki/karateclub/blob/462a9e8d9dcc5a0afc118e887eee80c332c16065/karateclub/estimator.py#L60).
* [`Estimator._check_graph`](https://github.com/benedekrozemberczki/karateclub/blob/462a9e8d9dcc5a0afc118e887eee80c332c16065/karateclub/estimator.py#L60) calls [`Estimator._check_connectivity`](https://github.com/benedekrozemberczki/karateclub/blob/462a9e8d9dcc5a0afc118e887eee80c332c16065/karateclub/estimator.py#L41), which calls [`nx.is_connected`](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.components.is_connected.html?highlight=is_connected#networkx.algorithms.components.is_connected).
* [`nx.is_connected`](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.components.is_connected.html?highlight=is_connected#networkx.algorithms.components.is_connected) raises an exception when a directed graph is given. 

I also noticed that [directed graphs cause an assertion violation when `Estimator._check_graph` is called](https://github.com/benedekrozemberczki/karateclub/blob/462a9e8d9dcc5a0afc118e887eee80c332c16065/karateclub/estimator.py#L47).

Does the HOPE implementation only support undirected graphs? This seems unintuitive to me since my understanding of the [HOPE paper](https://www.kdd.org/kdd2016/papers/files/rfp0184-ouA.pdf) was that one of the main benefits of HOPE was that it could embed nodes in a directed graph. 

Also, instead of having an exception be raised when a directed graph is given, can the directedness check happen first in [`Estimator._check_graph`](https://github.com/benedekrozemberczki/karateclub/blob/462a9e8d9dcc5a0afc118e887eee80c332c16065/karateclub/estimator.py#L60) to avoid this?

**Comment by benedekrozemberczki** [comment]
Please read the paper and the documentation.

**Comment by paul-tqh-nguyen** [comment]
One question about the documentation on HOPE: It seems that the documentation for HOPE has disappeared from readthedocs.

I cannot find anything on HOPE in the Neighbourhood-based Node Embedding section https://karateclub.readthedocs.io/en/latest/modules/root.html#neighbourhood-based-node-embedding .

The only thing I could find was that the HOPE paper was linked in the External Resources section https://karateclub.readthedocs.io/en/latest/notes/resources.html?highlight=asymmetric#neighbourhood-based-node-embedding .

When I use the search bar "hope" or "asymmetric", all I can find is the External Resources section linking the HOPE paper. 

Is there something obvious that I'm missing?

**Comment by benedekrozemberczki** [comment]
Read the Karate Club paper itself.
