### ISSUE TITLE
Numerical instability of NNSED

### ISSUE THREAD

**Issue by HushTheBlock** [benedekrozemberczki/karateclub#56]
When I implemented NNSED on my own network, I encountered the following problem:
> C:\Users\Administrator\anaconda3\lib\site-packages\karateclub\community_detection\overlapping\nnsed.py:75: RuntimeWarning: invalid value encountered in true_divide 
self._W = self._W*(enum/denom)

and this is caused by some zero entries in **denom**.
After adding the following codes, my issues are resolved successfully, and NNSED can now converge.
```
def _update_W(self, A):
        enum = A.dot(self._Z.T)
        denom_1 = self._W.dot(self._Z).dot(self._Z.T)
        denom_2 = (A.dot(A.transpose())).dot(self._W)
        denom = denom_1 + denom_2 + **1e-6**
        self._W = self._W*(enum/denom)

def _update_Z(self, A):
        enum = (A.dot(self._W)).transpose()
        denom = np.dot(np.dot(self._W.T, self._W), self._Z) + self._Z + **1e-6**
        self._Z = self._Z*(enum/denom)
```
I hope this could be fixed in the next version.

**Comment by benedekrozemberczki** [comment]
Could you open a PR?

**Comment by benedekrozemberczki** [comment]
Fixed it.

**Comment by HushTheBlock** [comment]
Sure thing. But I'm new to github so you may need to wait a while.
