### ISSUE TITLE
How to set the maximum node number in each community?

### ISSUE THREAD

**Issue by rann1018** [benedekrozemberczki/karateclub#59]
Hi,

Thanks for your good work! 

I want use community detection methods, such as GEMSEC, to separate the whole graph into
several non-overlapping subgraphs. At the same time, I want the maximum node number in
each subgraph is under a certain value, for example 100. How can I make this implement possible?

Looking forward for your attention and help.

**Comment by benedekrozemberczki** [comment]
Hi Rann1018,
