### ISSUE TITLE
weighted graphs 

### ISSUE THREAD

**Issue by almugabo** [benedekrozemberczki/karateclub#6]
Great package. Makes it very easy to experiment with newest algorithms. 
I have a question though: did I understand it correctly that it does not support weighted graphs ?

**Comment by benedekrozemberczki** [comment]
Not yet. After the first version of the paper about the package is out. i will try to work on extensions for heterogeneous, multiplex and weighted graphs.

**Comment by almugabo** [comment]
Thanks. Would help if I could. Great work this really advances the uptake of this line of research in applications. Thanks for this. Let’s close the issue for now
