### ISSUE TITLE
Community Detection on My Own Graph

### ISSUE THREAD

**Issue by rann1018** [benedekrozemberczki/karateclub#60]
Hi,

I try to conduct community detection on my own graph with GEMSEC example but an error raises:

File "/home/bright/.local/lib/python3.6/site-packages/karateclub/estimator.py", line 57, in _check_indexing
    assert numeric_indices == node_indices, "The node indexing is wrong."

The name of my node is a string type, I do not know whether this is the reason?
If I use my own graph for community detection, should I rename my node name from '1' to 'max_number'?

Thanks a lot for your attention and help.

**Comment by benedekrozemberczki** [comment]
Please read the research paper and the documentation.

**Comment by rann1018** [comment]
Oh, I see.
I miss the 'Standardized dataset ingestion' phase,  Thanks for your help.
