### ISSUE TITLE
Implementation of SF

### ISSUE THREAD

**Issue by andrewblance** [benedekrozemberczki/karateclub#61]
Hello,

I have been using the implementation of SF (details found in this paper: https://arxiv.org/pdf/1810.09155.pdf), and I am wondering if there is an inaccuracy.

I can create a graph like:

    mat = [[0,1,1,0],[1,0,0,0],[1,0,0,1],[0,0,1,0]]
    mat = np.matrix(mat)
    G = nx.from_numpy_matrix(mat)

I've pulled the code out of the class, and into a separate function, but it follows the same logic:

    def embedder(G, k):
        number_of_nodes = G.number_of_nodes()
        lap = nx.normalized_laplacian_matrix(G, nodelist=range(number_of_nodes))
        if number_of_nodes <= k:
            embedding = eigsh(lap, k=number_of_nodes-1, which='LM',
                              ncv=10*k, return_eigenvectors=False)
            shape_diff = k - embedding.shape[0] - 1
            embedding = np.pad(embedding, (1, shape_diff), 'constant', constant_values=0)
        else:
            embedding = eigsh(lap, k=k, which='LM',
                                      ncv=10*k, return_eigenvectors=False)
        return embedding

If we now test it with:

    embedder(G, len(G))

we get the result:

    array([0. , 0.5, 1.5, 2. ])

And then if we test:

    embedder(G, 2)

we get the answer:

    array([1.5, 2. ])

I get similar answers using the class itself. However, the paper states "We use the k smallest positive eigenvalues of L in ascending order as input of the classifier". For our first result, shouldn't the leading zero not be included (only positive eigenvalues). For our second we have accidentally chosen the largest two values - not the smallest.

A solution may be:

    def embedder(G, k):
        number_of_nodes = G.number_of_nodes()
        lap = nx.normalized_laplacian_matrix(G, nodelist=range(number_of_nodes))
    
        embedding = eigsh(lap, k=number_of_nodes-1, which='LM',
                          ncv=10*number_of_nodes, 
                          return_eigenvectors=False)
        
        embedding = embedding[embedding > 0]
        
        if len(embedding) < k:
            # since nodes < k, pad out the embedding
            shape_diff = k - embedding.shape[0]
            embedding = np.pad(embedding, (0, shape_diff), 'constant', constant_values=0)
    
        if len(embedding) > k:
            embedding = embedding[:k]
            
        return embedding

Now, the two answers we get are array([0.5, 1.5, 2. , 0. ]) and array([0.5, 1.5 ]). I believe this is more in line with the methodology the paper suggested.

**Comment by benedekrozemberczki** [comment]
Hi there, a few questions:

1. Is this a directed graph?
2. Is this connected?

**Comment by andrewblance** [comment]
Unless I have misunderstood, I think a graph with the adj matrix [[0,1,1,0],[1,0,0,0],[1,0,0,1],[0,0,1,0]] is un-directed and connected

**Comment by benedekrozemberczki** [comment]
Do you want to open a PR with the fix?

**Comment by benedekrozemberczki** [comment]
Okay. I will close this for now.
