### ISSUE TITLE
Question about overlapping community detecting algorithm.

### ISSUE THREAD

**Issue by zhqu1148980644** [benedekrozemberczki/karateclub#62]
Why the returned membership of each node is a single number, the belonging cluster is expected to an array in the sense of overlapping(each node may belong to multiple clusters). What's the difference between overlapping and non-overlapping detecting algorithms?

**Comment by benedekrozemberczki** [comment]
Non-overlapping: The node belongs to a single cluster.
Overlapping: We have a distribution over cluster memberships for each node.

Could you star the repo and hit follow?

**Comment by zhqu1148980644** [comment]
how can I fetch the distribution of each node and their corresponding belonging clusters.

**Comment by benedekrozemberczki** [comment]
The embeddings for example that you learn with these methods. Each row is an unnormalized distribution.

**Comment by zhqu1148980644** [comment]
thanks, I checked the embedding and find that it does not correlate well with the real clustering.
