### ISSUE TITLE
Documentation: Relationship with CDLib

### ISSUE THREAD

**Issue by BrandonKMLee** [benedekrozemberczki/karateclub#63]
It is known that https://github.com/GiulioRossetti/cdlib exists for the heavy inclusion of Community Detection algorithms:
- https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/node_clustering.html
- https://cdlib.readthedocs.io/en/latest/reference/evaluation.html

Are there any relations or collaborations between these two repos to compensate for algorithm incompleteness?

Also other discussions: https://github.com/GiulioRossetti/cdlib/issues/147

**Comment by benedekrozemberczki** [comment]
Hi Brandon, what do you mean?

**Comment by BrandonKMLee** [comment]
The current models included in KarateClub do not include some of the other Community Detection algorithms/models and Evaluation metrics implemented by CDLib, having a more streamlined solution that includes the use of NetworkX and/or iGraph (since iGraph is "faster" with C) would be very useful.
