### ISSUE TITLE
Question: New Fields of Role Analysis

### ISSUE THREAD

**Issue by BrandonKMLee** [benedekrozemberczki/karateclub#64]
There has been discussion before about a place to collect role discovery algorithms and that it is often referenced with other topics:
- https://github.com/GiulioRossetti/cdlib/issues/137 (Role Discovery)
- https://github.com/GiulioRossetti/cdlib/issues/149 (Brokers & Structural Holes)
- https://github.com/GiulioRossetti/cdlib/issues/148 (Centrality)

Is there any good way of relating these topics together in this repo?

**Comment by benedekrozemberczki** [comment]
Hi Brandon what do you mean axactly?

**Comment by BrandonKMLee** [comment]
Structural Node Level Embedding (Role2Vec) has been suggested to categorize nodes/vertex into sets of similar roles (those with similar connections), but yet I have not seen any reference of RolX or RoleSim yet. This leads me to question the difference between node characteristics/similarity and node clustering.
