### ISSUE TITLE
Questions regarding RMST-RBS

### ISSUE THREAD

**Issue by BrandonKMLee** [benedekrozemberczki/karateclub#65]
There is this paper called "Community detection and role identification in directed networks: understanding the Twitter network of the care.data debate" https://arxiv.org/abs/1508.03165, which follows "Interest communities and flow roles in directed networks: the Twitter network of the UK riots" https://arxiv.org/abs/1311.6785 and "Finding role communities in directed networks using Role-Based Similarity, Markov Stability and the Relaxed Minimum Spanning Tree" https://arxiv.org/abs/1309.1795

The papers mainly addresses the optimization of node embedding coupled with community detection as its main goal.
1. Are there any algorithms that does both of them at the same time? (e.g. Node2Vec)
2. Would RMST-RBS be included in KarateClub in the near future?

**Comment by BrandonKMLee** [comment]
Here is a library that might fix this issue: https://github.com/barahona-research-group/PyGenStability

**Comment by benedekrozemberczki** [comment]
If you would like to see these features, feel free to open a PR. Right now
I am mainly focusing on PyTorch Geometric Temporal.

**Comment by BrandonKMLee** [comment]
Understandable. The author have made note they will make this algorithm FOSS
https://github.com/barahona-research-group/PyGenStability/issues/35#issuecomment-845135117

**Comment by BrandonKMLee** [comment]
Also reading up on other embedding algorithms e.g. https://arxiv.org/pdf/1804.03733.pdf
