### ISSUE TITLE
'Graph2Vec' object has no attribute 'allow_disjoint'

### ISSUE THREAD

**Issue by tuhuynh-ds** [benedekrozemberczki/karateclub#67]
I tried Graph2Vec with PROTEINS dataset and they display error 'Graph2Vec' object has no attribute 'allow_disjoint'.
But when I tried with MUTAG dataset, Graph2Vec is run.
Please help me!

**Comment by parismic** [comment]
Could you please include some code references

**Comment by tuhuynh-ds** [comment]
thank you, i fixed this problem. The PROTEINS dataset has some non-connected graphs, so Graph2Vec raise error when run this data.
