### ISSUE TITLE
Get error when running tutorial code.

### ISSUE THREAD

**Issue by wanglu2014** [benedekrozemberczki/karateclub#68]
from karateclub.dataset import GraphReader

reader = GraphReader("twitch")

graph = reader.get_graph()
y = reader.get_target()
from karateclub import Diff2Vec

model = Diff2Vec(diffusion_number=2, diffusion_cover=20, dimensions=16)
model.fit(graph)
X = model.get_embedding()

Error is 
TypeError: __init__() got an unexpected keyword argument 'iter' 

in
![图片](https://user-images.githubusercontent.com/12541282/116108818-d7508780-a6e6-11eb-9d28-2383eb435c7f.png)

**Comment by benedekrozemberczki** [comment]
What is your gensim version?

**Comment by wanglu2014** [comment]
gensim==3.8.3
