### ISSUE TITLE
    assert connected or self.allow_disjoint, "Graph is not connected." AttributeError: 'Graph2Vec' object has no attribute 'allow_disjoint'

### ISSUE THREAD

**Issue by jiruhameru** [benedekrozemberczki/karateclub#71]
I am receiving this error after running the provided example on my own dataset: a set of sub-graphs, each representing one sessions of my experiment. 
How may solve this? 

The graph is un-directed and without features.

**Comment by SanderNugteren** [comment]
I also have a disjointed graph. Are there any Graph embedding methods where `allow_disjoint` is True? I tried searching through the library for `self.allow_disjoint = True`, but couldn't find any results.

If not, I'm contemplating introducing a dummy node into my graph which just connects to everything, but I don't know if that's a good approach or not, and if it works it would be a bit of a hack.

**Comment by benedekrozemberczki** [comment]
I will create a new release that will resolve this problem. Probably
tonight or tomorrow!

**Comment by benedekrozemberczki** [comment]
The newest 1.2.0 release resolves this issue. Please install and try it.

**Comment by SanderNugteren** [comment]
I tried the Deepwalk algorithm without introducing the fully connected dummy node, and my embeddings are much better now. Thanks!
