### ISSUE TITLE
How do I use my own data set and train.

### ISSUE THREAD

**Issue by fiego** [benedekrozemberczki/karateclub#73]
I have a directed graph of data, and I need to use graph embedding or node embedding to get the node embedding representation vector.

After reading the tutorial, I didn't find out how to use my own data.

1 Can you explain in code how to use my own data set?
2 Also, what should I do with my data set before it can be loaded?
3 And how do we get the embedded vector for this node after we train it?

**Comment by benedekrozemberczki** [comment]
The paper and the tutorial explain the input data requirements in great detail. If you need a node embedding you need a graph with numeric indices stored as a networkx graph. A graph embedding requires a list of networkx graphs. The documentation is explicit about these things. Could you star the repo and hit follow?
