### ISSUE TITLE
How to improve the performance of Graph2Vec model fit function ?

### ISSUE THREAD

**Issue by 1209973** [benedekrozemberczki/karateclub#76]
I tried to increase the performance of the Graph2Vec model by using increasing the worker parameter when initializing the model. But it seems that still, the model takes only 1 core to process the fit function. 

Is method I have used to assign the workers correct ?
Is there another method to improve the performance ?
``` python 
model =  Graph2Vec(workers=28)
graphs_list=create_graph_list(graph_df)
model.fit(graphs_list)
graph_x = model.get_embedding()
```

**Comment by benedekrozemberczki** [comment]
Most of the time is spent with WL hashing and that part only uses a single
core -  more cores are used during the embedding phase. If you read the
graphs from the disk you can use the approach that I have here:

https://github.com/benedekrozemberczki/graph2vec

Could you star the repos and hit follow on Github?

**Comment by 1209973** [comment]
Is it possible to optimizes the memory usage when training a graph embedding model like batch processing?
This is an option or workaround to do that, I find it hard to scale for large datasets.  
I tried to break a small dataset into smaller parts and try multiple fits but the resulting embeddings are quite different.

**Comment by 1209973** [comment]
In the end, I went with the FEATHER method since the FEATHER is more scalable than Graph2Vec and it is not transductive.

**Comment by benedekrozemberczki** [comment]
FEATHER scales well, it is indeed inductive and more expressive. It is SOTA on this dataset too: https://openreview.net/forum?id=1xDTDk3XPW (which is extremely cool considering the dataset size).

**Comment by benedekrozemberczki** [comment]
@1209973 The newest release has an inference functionality.
