### ISSUE TITLE
GEMSEC experimental results is not good enough.

### ISSUE THREAD

**Issue by yuxy2018** [benedekrozemberczki/karateclub#77]
Hi,

I tried to use the gemsec example to conduct community detection on the Facebook-Politicians dataset in the paper, but the experimental results show that the modularity is only 0.5, which is not as good as benedekrozemberczki/Gemsec result 0.85.
What hyperparameter should be used？

Thanks a lot for your attention and help.

**Comment by benedekrozemberczki** [comment]
Could you try the original implementation?

**Comment by yuxy2018** [comment]
user original implementation in https://github.com/benedekrozemberczki/GEMSEC, result is 0.85.

**Comment by benedekrozemberczki** [comment]
Could you star the repo?
