### ISSUE TITLE
Breaking change in Gensim

### ISSUE THREAD

**Issue by br0kej** [benedekrozemberczki/karateclub#78]
Hi, 

I came across `karateclub` today and thought I would begin to have an experiment with the algorithms on offer. Immediately after install following the guide I ran into an odd `numpy` error in `gensim` exactly the same as  RaRe-Technologies/gensim/issues/3226. 

The fix seems to be pinning `numpy` to version `1.19.2` whilst the `gensim` folks track down what the cause is

**Comment by benedekrozemberczki** [comment]
Cheers!

**Comment by benedekrozemberczki** [comment]
Can you open a PR?
