### ISSUE TITLE
Question about support for Graphs with Entity Types

### ISSUE THREAD

**Issue by sid-sundrani** [benedekrozemberczki/karateclub#83]
Wanted to check if there are any unsupervised learning based methods to learn graph embeddings that take advantage of node entity types? I see the implementations of Proximity Preserving Node Embeddings. If a graph has more than one node type (such as knowledge graphs) , are there any implementations that use the node type of each node or edge?

**Comment by benedekrozemberczki** [comment]
Most of the algorithms are not designed for those graphs! Checkout PyKeen - that might help you!
