### ISSUE TITLE
Incorrect default value in documentation

### ISSUE THREAD

**Issue by tapadeep** [benedekrozemberczki/karateclub#85]
The default value of ```epochs``` is given in the documentation of [AE](https://karateclub.readthedocs.io/en/latest/modules/root.html#karateclub.node_embedding.attributed.ae.AE) and [MUSAE](https://karateclub.readthedocs.io/en/latest/modules/root.html#karateclub.node_embedding.attributed.musae.MUSAE) as 1, when the source code has the value 5. Do change it.

**Comment by benedekrozemberczki** [comment]
How about you open a PR?
