### ISSUE TITLE
Feather Node output length feature embedding

### ISSUE THREAD

**Issue by umbylyno** [benedekrozemberczki/karateclub#86]
Hi everybody, I have a question. 

Is it possible to define the number of outputs embeddings with Feather node method? I am trying to implement it in my system as a feature extractor of a knowledge graph, but every time I apply it I have different lengths. 

Thanks in advance.

**Comment by benedekrozemberczki** [comment]
Dear @umbylyno,

It is 2 * scale * number_of_evaluation points. Take a look at the FEATHER paper, it explains why this is the case. 

Could you star the repo?

Bests,

Benedek
