### ISSUE TITLE
Is consecutive numeric indexing necessary for Graph2Vec?

### ISSUE THREAD

**Issue by bdeng3** [benedekrozemberczki/karateclub#87]
Thanks for the awesome work, networkx is truly helpful when we are dealing with Graph data structure.

I'm trying to get graph embedding using Graph2vec so that we could compare similarity among graphs. But I'm stuck in this assertion: `assert numeric_indices == node_indices, "The node indexing is wrong."`

Say if we have two graphs, each node in the graph represents a word. We build a mapping so that we could replace text with number. For example, whenever the word "Library" occurs in any graph, we label it with the number "2". In this case, the indexes inside one graph might not be consecutive because the mapping is created from a number of graphs.

So is it still necessary for enforce consecutive indexing in this case? Or I understand the usage of Graph2Vec wrong?

**Comment by benedekrozemberczki** [comment]
Yeah but node fearures can be shared and be independent of indexing.

**Comment by bdeng3** [comment]
Thanks for the quick reply!! Do you mean literally adding a “feature” attribute to the node, like you mentioned in the paper? Or we could add as many features as we wanted to the node?


Best,
Botao Deng

________________________________

**Comment by benedekrozemberczki** [comment]
A single string per node.

**Comment by benedekrozemberczki** [comment]
Can you cite the Karateclub paper?

**Comment by bdeng3** [comment]
> Can you cite the Karateclub paper?

Sure. Below is the description of the paper: (Section 3.6 - Limitations)

> The Weisfeiler-Lehman feature based embedding techniques allow nodes to have a single string feature which can be accessed with the feature key. Without the presence of this key these algorithms default to the use of degree centrality as a node feature.

So if I understand correctly. When we used KarateClub's implementation of Graph2Vec, we could create a node like this: 

`graph.add_note(numeric_id, feature = "actual_content")`

I'm not entirely sure if this is the expected way to do it since I'm pretty new in the field of Graph. I'm just concerned the Graph2Vec algorithm fails to recognize that `Node(numeric_id = 2, "Library")` in graph1 is actually the same thing as `Node(numeric_id = 45, "Library")` in another Graph.

**Comment by helen-ww** [comment]
Hi, I have the same question with you. Now, I try to add the features to the same type of nodes.   Have you solved the following problems?
```
I'm not entirely sure if this is the expected way to do it since I'm pretty new in the field of Graph. I'm just concerned the Graph2Vec algorithm fails to recognize that Node(numeric_id = 2, "Library") in graph1 is actually the same thing as Node(numeric_id = 45, "Library") in another Graph.
```
