### ISSUE TITLE
graphwave changing structure of matrix and gives warning

### ISSUE THREAD

**Issue by jhammarstedt** [benedekrozemberczki/karateclub#88]
Hi,
I'm encountering "[WARNING](pygsp.graphs.graph.check_weights): The main diagonal of the weight matrix is not 0!" when running GraphWave.fit(G)

When passed in to .fit() my graph has a 0 diagonal. But after running the GraphWave.fit() the diagonal changes to 1 and I get the warning. Is this expected?

**Comment by laurahdezlorenzo** [comment]
Hi!

I'm encountering the same warning when using GraphWave. Any updates about this?

**Comment by LucaCappelletti94** [comment]
No worries. Please do feel free to re-open this issue if the warning turns out to be more problematic than expected.
