### ISSUE TITLE
Support for incremental training?

### ISSUE THREAD

**Issue by bdeng3** [benedekrozemberczki/karateclub#89]
Currently if we wanted to train a model, we call the "fit" method who takes in a list of networkX graphs. 

What if we have a really large number of graphs that can not be fit into RAM, is incremental training supported?

**Comment by benedekrozemberczki** [comment]
Do you want to open a PR?

**Comment by benedekrozemberczki** [comment]
Dear @bdeng3,

The newest 1.3.0. release on PyPI can handle inference! Can you star the repo and hit star?

Benedek
