### ISSUE TITLE
Infer new graph embeddings

### ISSUE THREAD

**Issue by juliolopes98** [benedekrozemberczki/karateclub#92]
Hello all! 

Is it possible, based on a previous set of graphs, to infer a new, previously unseen, graph embedding? A similar thing happens in Doc2Vec, is it possible here?

Thank you for your nice work!

Júlio Lopes

**Comment by benedekrozemberczki** [comment]
Yes, I could create an infer method - it would need the same API for all of the graph level methods. Do you want to be involved with the development and design @juliolopes98 ?

**Comment by juliolopes98** [comment]
Seems a really good idea, at this point I'm a master student, so I don't have any experience in open-source projects. If you prefer, you can contact me, via email: juliolopes@ipb.pt.

**Comment by benedekrozemberczki** [comment]
Dear @juliolopes98,

The newest 1.3.0. release on PyPI can handle inference! Can you star the repo and hit star?

Benedek
