### ISSUE TITLE
embeddings error

### ISSUE THREAD

**Issue by riyaj8888** [benedekrozemberczki/karateclub#95]
Hi 
I am trying to create node embeddings using following code block.

`import networkx as nx
from karateclub import DeepWalk

g = networkx_graph 

model = DeepWalk()
model.fit(g)
embedding = model.get_embedding()`

# error: 
ssertionError: The node indexing is wrong.

**Comment by benedekrozemberczki** [comment]
Your nodes should have a numeric index like 0,1,..., n-1
