### ISSUE TITLE
deepwalk error

### ISSUE THREAD

**Issue by riyaj8888** [benedekrozemberczki/karateclub#97]
i am using networkx graph as input for generating deepwalk embeddings but after 
model.fit(graph) getting following error.
can u tell what went wrong?

Python38\site-packages\karateclub\utils\walker.py:50, in RandomWalker.do_walks(self, graph)
     48 self.graph = graph
     49 for node in self.graph.nodes():
---> 50     for _ in range(self.walk_number):
     51         walk_from_node = self.do_walk(node)
     52         self.walks.append(walk_from_node)

TypeError: 'tuple' object cannot be interpreted as an integer

**Comment by benedekrozemberczki** [comment]
@riyaj8888 ?
