### ISSUE TITLE
Understanding Graph2Vec implementation

### ISSUE THREAD

**Issue by Moooser** [benedekrozemberczki/karateclub#98]
Dear developers,

Thanks for providing such an amazing framework!
I have troubles understanding the graph2vec implementation. The assumption for each graph is, that nodes are indexed consecutively, beginning with zero. But of course, when creating a graph embedding, not every graph consists out of the same nodes. Because of that, nodes can't be labeled uniquely. Shouldn't this be a problem or am I missunderstanding graph2vec/ WL kernels?

Best Regards 

Sandro

**Comment by benedekrozemberczki** [comment]
Hi there, I would suggest reading the Graph2Vec and WL kernel papers in depth.
