### ISSUE TITLE
Graph2Vec Error

### ISSUE THREAD

**Issue by rodrigo-arenas** [benedekrozemberczki/karateclub#99]
Hi, I'm trying to use Graph2Vec with a simple DiGraph but I'm getting an error; I'm quite new to the package so I'm not sure if I'm doing something wrong.
I'm using networkx version 2.6.3 and karateclub 1.3.0

```python
import networkx as nx
from karateclub.graph_embedding import Graph2Vec

edge_list = [('A', 'B'), ('B', 'C'), ('C', 'D'), ('D', 'J'),
             ('D', 'I'), ('J', 'I'), ('I', 'F'), ('I', 'E'),
             ('I', 'L'), ('F', 'D'), ('E', 'K'), ('K', 'I'), ('L', 'M')]

G = nx.DiGraph()
for edge in edge_list:
    G.add_edge(*edge)

graph_vect = Graph2Vec()
graph_vect.fit([G])
```

I get the following error:
![image](https://user-images.githubusercontent.com/31422766/175066619-c35fcc87-0bfa-4d08-bc8d-9f2d043aa73e.png)

**Comment by benedekrozemberczki** [comment]
Please read the paper - node indices should be numbers starting with 0.
